### PR TITLE
Add support for splitting configurations into separate files

### PR DESCRIPTION
**Pull request by sil2100**
Add a new config option 'include' that allows to include config options from a separate file or directory. Add a test suite for the conf part. Issue: #586 .

### CODE REVIEW

**Comment by sil2100** [comment]
This is a very simple approach. It might be good to add some checks for infinite include loops in configuration files.

**Comment by sil2100** [comment]
This is now good. Seems like I got used to Python3 too much.

**Comment by hglkrijger** [comment]
@sil2100 - could you sign the CLA?

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by hglkrijger** [comment]
@brendandixon @jinhyunr any other feedback?

**Comment by hglkrijger** [comment]
@sil2100 I believe we came to the conclusion on our call last week that this was not needed.

**Comment by sil2100** [comment]
Yes, although we still think it would be a valuable addition. But it's not blocking us anymore, yes.

**Pull request closed without merging**
