### PR TITLE
Use fallocate where possible [2.1]

### PR DESCRIPTION
**Pull request by hglkrijger**
try to use posix.fallocate or fallocate before falling back to dd; adds unit tests for basic functionality and shellutil.quote. addresses #127

### CODE REVIEW

**Comment by hglkrijger** [comment]
this also replaces #128 

/cc @jasonzio @Arthur2e5

**Comment by Arthur2e5** [comment]
Do I need to sign a CLA for the "Copyright 2014 Microsoft Corporation" part?

**Comment by ahmetalpbalkan** [comment]
@Arthur2e5 ideally yes, it appears like this repository is not enabled for the CLA bot.

**Comment by ahmetalpbalkan** [comment]
We just enabled the CLA bot on this repo. It makes sense for @Arthur2e5 to take over this patch, amend the commit with his name and send a new PR so tha CLA bot kicks off and he can sign the CLA.

**Comment by hglkrijger** [comment]
Sure, either way is fine with me. I just did the rebasing; @Arthur2e5, would you like to take this back, or shall I merge for you?

**Comment by Arthur2e5** [comment]
Forking and starting a new PR.

**Comment by Arthur2e5** [comment]
#215.

**Comment by hglkrijger** [comment]
replaced by #207

**Pull request closed without merging**
