### PR TITLE
Add support for VMware PhotonOS

### PR DESCRIPTION
**Pull request by sshedi**
Signed-off-by: Shreenidhi Shedi <sshedi@vmware.com>
Signed-off-by: Shreenidhi Shedi <yesshedi@gmail.com>

## Description

Issue # 

---

### PR information
- [x] The title of the PR is clear and informative.
- [] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [x] New Unit tests were added for the changes made

### Quality of Code and Contribution Guidelines
- [x] I have read the [contribution guidelines](https://github.com/Azure/WALinuxAgent/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sshedi** [comment]
Can somebody help me out with the failed tests? Not sure what's going wrong.

**Comment by larohra** [comment]
> Can somebody help me out with the failed tests? Not sure what's going wrong.

Sorry about that, looks like we had a couple of flaky tests that were failing. A retry fixed those.

**Comment by sshedi** [comment]
Thanks @larohra Do I need to do any further changes in this PR?

**Review by larohra — APPROVED** [review]
LGTM. @dhivyaganesan can you review it too please. I'll run DCR on the side

**Comment by larohra** [comment]
DCR looks good - https://tuxgold.corp.microsoft.com/job/AzLinux/job/DungeonCrawler/job/DungeonCrawler.larohra3/219/

@dhivyaganesan feel free to merge the changes if it looks good to you

**Review by dhivyaganesan — APPROVED** [review]

**Review by larohra — APPROVED** [review]

**Comment by sshedi** [comment]
Thanks for all the assistance. Have a nice time ahead.

**Pull request merged**
