### PR TITLE
Change the way the PA checks for cloud-init existence and status

### PR DESCRIPTION
**Pull request by trstringer**
## Description

This PR changes the way that the provisioning agent in walinuxagent determines if cloud-init is already acting as the provisioning agent. This uses unit/service status to make this determination, instead of reading processes. This should be a more reliable implementation to make the correct determination. And it also reuses existing logic in walinuxagent for this discovery.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and Travis.CI is passing.

### Quality of Code and Contribution Guidelines
- [ ] I have read the [contribution guidelines](https://github.com/Azure/WALinuxAgent/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by narrieta** [comment]
LGTM; running automation

**Comment by trstringer** [comment]
@narrieta, I fixed the unit tests. The reason they were passing on our local machines is because we didn't have cloud-init installed on the test host. Therefore the call to `azurelinux.pa.provision.cloudinitdetect.cloud_init_is_enabled` came back `False`. But it seems like on the CI servers there probably was cloud-init installed and enabled, and it was causing the failure then. All I had to do was mock this function to return `False`.

Now that the tests are passing, this PR should be ready for re-review.

**Comment by narrieta** [comment]
@trstringer thanks; running automation

**Comment by narrieta** [comment]
automation ok

**Review by narrieta — APPROVED** [review]

**Review by kevinclark19a — APPROVED** [review]

**Review by pgombar — APPROVED** [review]

**Comment by anhvoms** [comment]
LGTM

**Review by anhvoms — APPROVED** [review]

**Comment by trstringer** [comment]
Thanks, all, for the reviews! @narrieta, let me know if there's anything else you need from me prior to merging.

**Comment by narrieta** [comment]
@trstringer Just waiting for the Travis run to complete. Travis has been extremely slow these days. It seems like your run is still queued.

**Pull request merged**
