### PR TITLE
Use fallocate where possible [2.1] (#207)

### PR DESCRIPTION
**Pull request by Arthur2e5**
try to use posix.fallocate or fallocate before falling back to dd; adds unit tests for basic functionality and shellutil.quote. addresses #127

..

### CODE REVIEW

**Comment by Arthur2e5** [comment]
I forgot to amend the commit.. Just did a force push, I guess it should work now.

**Comment by ahmetalpbalkan** [comment]
@Arthur2e5 oops I should have said `git rebase origin/develop`. It looks like there are still some conflicts.

**Comment by Arthur2e5** [comment]
`git pull --rebase=preserve https://github.com/Azure/WALinuxAgent develop`.

**Comment by hglkrijger** [comment]
lgtm. @ahmetalpbalkan - any objections?

**Comment by ahmetalpbalkan** [comment]
@hglkrijger it looks like it got merge conflicts again. I think the code has been reviewed before, my question would be, does the unit test here get executed by the CI?

@Arthur2e5 it looks like our CLA bot is not really activated properly on this repo yet. In the meanwhile can you please sign our CLA?  It's all electronic and will take just minutes. https://cla.azure.com.

**Comment by hglkrijger** [comment]
@ahmetalpbalkan yes, the travis config should enable discovery and execution of all tests.

**Comment by Arthur2e5** [comment]
CLA signed.

**Pull request merged**
