### PR TITLE
Removed threading for RDMA

### PR DESCRIPTION
**Pull request by edwardsp**
There are issues where about 5% of nodes fail to initialise the RDMA on a reboot.  The problem shows as a defunct process that was created with the run_get_output function in the shellutil.py.  This is when Python 2.7 is used and is probably related to the thread safety issues of the subprocess module.  This stackoverflow page gives a description and links to bugs - https://stackoverflow.com/questions/21194380/is-subprocess-popen-not-thread-safe.  The thread seems an unnecessary optimisation as the RDMA initialisation runs in under 0.1s.

Note: this should not be an issue with Python 3 but this is not standard for most OSs.  Another alternative could be to make it Python 3 only and release the azurelinuxagent as a packaged executable.

## Description

Issue # 

---

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and Travis.CI is passing.

### Quality of Code and Contribution Guidelines
- [ ] I have read the [contribution guidelines](https://github.com/Azure/WALinuxAgent/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by longlimsft** [comment]
Thanks @edwardsp.

We are doing regression tests and will update after tests are done.

**Comment by vrdmr** [comment]
@longlimsft Any updates on the regression tests? Thanks.

**Comment by juhlee-microsoft** [comment]
> Testing in progress,
> @juhlee-microsoft please update when tests are done.

**Signed-off**

> All 47 regression tests (BVT, Smoke, Network, WALA, Smoke, DPDK, GPU, Nested, Storage, Community, Perf, Stress, IB) against CentOS 6.5, 6.8, 6.10, 7.1, 7.4, 7.5 HPC, SUSE 12 sp3 HPC, and Ubuntu 16.04 LTS are done. All passed except a few failed/abort. Those failed test case and aborted ones are from automation infra issue or unsupported by kernel.

**Comment by jeking3** [comment]
Is the issue here that threading is used, or that nothing swings back around to join the thread?  I see nothing that does that, so how do you know if it finished?

**Pull request merged**
