### PR TITLE
Don't set default gateway if one exists (+freebsd)

### PR DESCRIPTION
**Pull request by szarkos**

### CODE REVIEW

**Comment by szarkos** [comment]
Let's hold off on merging until Brendan signs off.

**Comment by hglkrijger** [comment]
@szarkos - same for this one, is this a simple port over in the 2.1 branch?

**Comment by szarkos** [comment]
Last I spoke with Brendan he wanted to remove this functionality entirely from the 2.1 agent.  So if we're not fixing the 2.0 branch anymore then we can just close this PR and Brendan can proceed with removing the default gateway functionality from 2.1.

**Comment by hglkrijger** [comment]
ok, will close this one.

/cc @brendandixon

**Pull request closed without merging**
