### PR TITLE
Remove unnecessary sleep and increase poll rate

### PR DESCRIPTION
**Pull request by dwj300**

### CODE REVIEW

**Comment by brendandixon** [comment]
@dwj300 These numbers, while the may seem long, are necessary for a few cases. Further, most of Ubuntu initialization is handled by cloud-init.

**Comment by dwj300** [comment]
Any update on this?

**Comment by hglkrijger** [comment]
@dwj300, did you see the comment from @brendandixon?

Is this poll rate causing you issues?

**Comment by dwj300** [comment]
Yes, and I have been working with him offline to flight the change and
collect data.

**Comment by brendandixon** [comment]
@dwj300 Accepting.

**Pull request merged**
