### PR TITLE
SUSE config: use Btrfs LZO compression for ResourceDisk

### PR DESCRIPTION
**Pull request by ddiss**
Btrfs provides support for transparent compression, which can be
requested at mount time via the compress=type[:level] mount option.

As demonstrated in [1], transparent LZO compression provides a good
trade-off between compression ratio and performance, while also being
supported by legacy SUSE kernels. zstd could be considered for
modern SLE15-SP1+ / openSUSE Leap 15.1+ kernels.

Amongst other benefits, moving from ext4 to Btrfs allows for ephemeral
ResourceDisk data to be periodically and incrementally backed-up to
regular Page Blob backed disks using btrfs send/recv.

1. Btrfs compression benchmarks
   mainline kernel commit: 5c1aab1dd5445ed8bdcdbb575abc1b0d7ee5b2e7

Signed-off-by: David Disseldorp <ddiss@suse.de>

## Description

Issue # 

---

### PR information
- [x ] The title of the PR is clear and informative.
- [x ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and Travis.CI is passing.

### Quality of Code and Contribution Guidelines
- [x ] I have read the [contribution guidelines](https://github.com/Azure/WALinuxAgent/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ddiss** [comment]
@rjschwei please review

**Review by rjschwei — DISMISSED** [review]

**Comment by ddiss** [comment]
Thanks a lot for the review, Robert.
Code owners: Please let me know if anything's needed from me to move this along.

**Comment by narrieta** [comment]
@trstringer could you take a look? thanks!

**Comment by trstringer** [comment]
Something to consider is that the SUSE images using cloud-init as the provisioning agent seem to be using ext4. Here's the resource disk of the `suse:sles-15-sp2:gen1:latest` image:

```
$ df -T /dev/sdb1
Filesystem     Type 1K-blocks  Used Available Use% Mounted on
/dev/sdb1      ext4   7157240 32248   6741712   1% /mnt
```

So users going from walinuxagent -> cloud-init would introduce a change from btrfs -> ext4 now with this PR. This is not necessarily a blocking issue for me, but let me know your thoughts on that change, @rjschwei.

**Comment by rjschwei** [comment]
@trstringer yes, we switched all images to use cloud-init per customer requests and downstream work for image build setup is required. This change is for those that pull the agent directly from GitHub or build custom images that use the agent package we (SUSE) provides and do not use cloud-init.

**Comment by trstringer** [comment]
@rjschwei, ok that makes sense. So if you're fine with the different resource disk filesystems between waagent and cloud-init for SUSE images, that works for me.

**Review by trstringer — APPROVED** [review]

**Comment by narrieta** [comment]
running automation

**Comment by narrieta** [comment]
Automation OK

**Review by narrieta — APPROVED** [review]

**Review by kevinclark19a — APPROVED** [review]

**Comment by narrieta** [comment]
@ddiss - could you bring your branch up to date with develop? thanks!

**Comment by ddiss** [comment]
> @ddiss - could you bring your branch up to date with develop? thanks!

Done, thanks

**Review by narrieta — APPROVED** [review]

**Review by pgombar — APPROVED** [review]

**Pull request merged**
