### PR TITLE
Debian - Byte to string conversion for systemd service creation

### PR DESCRIPTION
**Pull request by thedarksage**
## Description

Issue # (https://github.com/Azure/WALinuxAgent/issues/2573)

Added string decode for byte to string conversion while checking for presence of systemd

return from subprocess.check_output(['cat', '/proc/1/comm']).strip() for python3 ===> b'systemd'
return from subprocess.check_output(['cat', '/proc/1/comm']).strip() for python2 ===> 'systemd'

https://github.com/Azure/WALinuxAgent/issues/2573
-->

---

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made

### Quality of Code and Contribution Guidelines
- [x] I have read the [contribution guidelines](https://github.com/Azure/WALinuxAgent/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thedarksage** [comment]
return from subprocess.check_output(['cat', '/proc/1/comm']).strip() for python3 ===> b'systemd'
return from subprocess.check_output(['cat', '/proc/1/comm']).strip() for python2 ===> 'systemd'

https://github.com/Azure/WALinuxAgent/issues/2573

**Comment by nagworld9** [comment]
Since DCR pipeline is not working, I manually tested and looks good.

**Comment by nagworld9** [comment]
@thedarksage Thanks for the fix.

**Review by nagworld9 — APPROVED** [review]

**Comment by larohra** [comment]
> Since DCR pipeline is not working, I manually tested and looks good.

@nagworld9 did you test this `setup.py` works for Debian images with py2 as default too?

**Comment by nagworld9** [comment]
> > Since DCR pipeline is not working, I manually tested and looks good.
> 
> @nagworld9 did you test this `setup.py` works for Debian images with py2 as default too?

The Debian image that I tested had both py2 and py3. So, I ran setup.py with both pythons and it worked.
Additionally, we have decided to do DCR run to make sure of that.

**Review by larohra — APPROVED** [review]

**Pull request merged**
