### PR TITLE
Write correct extension version in HandlerEnvironment.json

### PR DESCRIPTION
**Pull request by hosungsmsft**
Addressing issue #189.

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@hosungsmsft that 1.0 is indicating the v1.0 of the handlerenvironment schema; not the extension handler version.

image

**Comment by hosungsmsft** [comment]
Thanks @ahmetalpbalkan . Then I guess we'll have to fix the following line in the extension's handler util. Will look from that direction, and close this later as such.

https://github.com/Azure/azure-linux-extensions/blob/master/Utils/HandlerUtil.py#L178

**Comment by ahmetalpbalkan** [comment]
@hosungsmsft yes, and erroring out if `version <> 1.*` might be the best practice to apply.

**Comment by ahmetalpbalkan** [comment]
@hosungsmsft also please open PRs from your forked repo, otherwise it causes new unattended branches in Azure repo which needs to be cleaned up by humans.

**Pull request closed without merging**
