### PR TITLE
Add uos support

### PR DESCRIPTION
**Pull request by weidongkl**
Signed-off-by: weidong <weidong@uniontech.com>

## Description

Issue # 

---

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [x] New Unit tests were added for the changes made

### Quality of Code and Contribution Guidelines
- [x] I have read the [contribution guidelines](https://github.com/Azure/WALinuxAgent/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by larohra — COMMENTED** [review]
changes LGTM, running automation will approve once I get a green run.

**Review by larohra — APPROVED** [review]
[DCR looks ](https://tuxgold.corp.microsoft.com/job/AzLinux/job/DungeonCrawler/job/DungeonCrawler.larohra3/218/artifact/results/) good (apart from known unrelated errors)

@dhivyaganesan can you take a look too please.

**Review by dhivyaganesan — APPROVED** [review]

**Comment by weidongkl** [comment]
@larohra This PR has not been merged yet. Do I need to make any changes

**Comment by larohra** [comment]
> @larohra This PR has not been merged yet. Do I need to make any changes

Done! Sorry for the delay and thanks for your contribution!

**Pull request merged**
