### PR TITLE
Implement Fedora disto

### PR DESCRIPTION
**Pull request by vittyvk**
Fedora distribution is not covered by Redhat*OS* classes, create
a separate one for it.

Note: this patch was previosly carried out-of-tree, fedora packages
already have it included.

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>

## Description

Issue # 

---

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made

### Quality of Code and Contribution Guidelines
- [ ] I have read the [contribution guidelines](https://github.com/Azure/WALinuxAgent/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cjp256** [comment]
@narrieta can you take a look at this PR? Would be a great starting point for Fedora support.

**Comment by narrieta** [comment]
@vittyvk Sorry, for the delay. LGTM, will do one automation run and merge when it completes.

You tested your changes on your side, correct? Currently we do not have the infrastructure to test Fedora.

**Comment by vittyvk** [comment]
@narrieta Yes, Fedora was carrying these patches for some time already. I'm smoke-testing every new Fedora build (I'm the package maintainer).

**Review by narrieta — APPROVED** [review]

**Comment by narrieta** [comment]
@vittyvk Thank you. Merged.

**Pull request merged**
