### PR TITLE
Clean up the CoreOS osutil class

### PR DESCRIPTION
**Pull request by dm0-**

### CODE REVIEW

**Comment by hglkrijger** [comment]
lgtm.

@ahmetalpbalkan, @brendandixon - any other comments?

**Comment by ahmetalpbalkan** [comment]
Looks good. Are the coreos images picking up 2.1.x?

**Comment by brendandixon** [comment]
lgtm

**Comment by dm0-** [comment]
The [current ebuild](https://github.com/coreos/coreos-overlay/blob/master/app-emulation/wa-linux-agent/wa-linux-agent-2.1.3-r2.ebuild) is 2.1.3, and I am looking into updated to the latest version now.

**Pull request merged**
