### PR TITLE
Honor metadata etag for get_certs path.

### PR DESCRIPTION
**Pull request by adepue**
## Description

Issue # 

---

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and Travis.CI is passing.

### Quality of Code and Contribution Guidelines
- [ ] I have read the [contribution guidelines](https://github.com/Azure/WALinuxAgent/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adepue** [comment]
@narrieta for feedback

**Comment by narrieta** [comment]
Change looks ok. Running automation.

**Comment by adepue** [comment]
@narrieta Seems that the etag value wasn't ever being passed up to the server either.  I have added another commit here that addresses that.  Let me know what you think.

**Comment by adepue** [comment]
The entire restutil class here doesnt seem to honor the 304 response codes per the protocol.  I am going to close this PR for now and will bring it back once we have fully verified the failure patterns.  Sorry for the scramble @narrieta

**Comment by narrieta** [comment]
@adepue No problem, thanks!

**Comment by adepue** [comment]
@narrieta I have updated to incorporate handling of 304 return codes in a way isolated to the metadata protocol only.  Let me know what you think of the code structure.  We have a setup we can test on once we are fine with the code approach.

**Comment by adepue** [comment]
@narrieta Let me know if you have concerns with this approach/update at all.

**Pull request merged**
