### PR TITLE
Reduce chatty logs #275

### PR DESCRIPTION
**Pull request by brendandixon**
Correct #275.
Signed-off-by: Brendan Dixon <brendand@microsoft.com>

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
LGTM thanks.

**Comment by ahmetalpbalkan** [comment]
@brendandixon just realized this does not reduce the noise for `Uploading status blob succeeded` log line. Should we make that verbose, too?

**Comment by brendandixon** [comment]
@ahmetalpbalkan Sure. I'll poke around.

**Comment by ahmetalpbalkan** [comment]
Would be great, currently the past 20 mins:


```
2016/06/29 20:29:29.648090 INFO Azure Linux Agent Version:2.1.5.rc2
2016/06/29 20:29:29.648454 INFO OS: centos 6.5
2016/06/29 20:29:29.648806 INFO Python: 2.6.6
2016/06/29 20:29:29.649370 INFO Daemon is already running: 39625
2016/06/29 20:29:37.210827 INFO Azure Linux Agent Version:2.1.5.rc2
2016/06/29 20:29:37.211238 INFO OS: centos 6.5
2016/06/29 20:29:37.211619 INFO Python: 2.6.6
2016/06/29 20:29:37.211839 INFO Daemon is already running: 39625
2016/06/29 20:29:52.370459 INFO Uploading status blob succeeded
2016/06/29 20:30:18.493928 INFO Uploading status blob succeeded
2016/06/29 20:30:43.707103 INFO Uploading status blob succeeded
2016/06/29 20:31:08.943713 INFO Uploading status blob succeeded
2016/06/29 20:31:35.147714 INFO Uploading status blob succeeded
2016/06/29 20:32:00.343316 INFO Uploading status blob succeeded
2016/06/29 20:32:25.548115 INFO Uploading status blob succeeded
2016/06/29 20:32:51.696018 INFO Uploading status blob succeeded
2016/06/29 20:33:16.903407 INFO Uploading status blob succeeded
2016/06/29 20:33:42.051509 INFO Uploading status blob succeeded
2016/06/29 20:34:08.201743 INFO Uploading status blob succeeded
2016/06/29 20:34:33.351242 INFO Uploading status blob succeeded
2016/06/29 20:34:58.504425 INFO Uploading status blob succeeded
2016/06/29 20:35:24.666142 INFO Uploading status blob succeeded
2016/06/29 20:35:49.879560 INFO Uploading status blob succeeded
2016/06/29 20:36:15.083768 INFO Uploading status blob succeeded
2016/06/29 20:36:41.233983 INFO Uploading status blob succeeded
2016/06/29 20:37:06.372621 INFO Uploading status blob succeeded
2016/06/29 20:37:31.534165 INFO Uploading status blob succeeded
2016/06/29 20:37:57.696711 INFO Uploading status blob succeeded
2016/06/29 20:38:22.913093 INFO Uploading status blob succeeded
2016/06/29 20:38:48.128185 INFO Uploading status blob succeeded
2016/06/29 20:39:14.257721 INFO Uploading status blob succeeded
2016/06/29 20:39:39.471008 INFO Uploading status blob succeeded
2016/06/29 20:40:04.670312 INFO Uploading status blob succeeded
2016/06/29 20:40:30.830402 INFO Uploading status blob succeeded
2016/06/29 20:40:56.033325 INFO Uploading status blob succeeded
2016/06/29 20:41:21.173583 INFO Uploading status blob succeeded
2016/06/29 20:41:47.422715 INFO Uploading status blob succeeded
2016/06/29 20:42:12.569223 INFO Uploading status blob succeeded
2016/06/29 20:42:37.750920 INFO Uploading status blob succeeded
2016/06/29 20:43:03.892781 INFO Uploading status blob succeeded
2016/06/29 20:43:29.104348 INFO Uploading status blob succeeded
2016/06/29 20:43:54.370011 INFO Uploading status blob succeeded
2016/06/29 20:44:20.522555 INFO Uploading status blob succeeded
2016/06/29 20:44:45.728618 INFO Uploading status blob succeeded
2016/06/29 20:45:10.890813 INFO Uploading status blob succeeded
2016/06/29 20:45:37.083084 INFO Uploading status blob succeeded
2016/06/29 20:46:02.289190 INFO Uploading status blob succeeded
2016/06/29 20:46:27.417398 INFO Uploading status blob succeeded
2016/06/29 20:46:53.569546 INFO Uploading status blob succeeded
2016/06/29 20:47:18.775648 INFO Uploading status blob succeeded
2016/06/29 20:47:43.983852 INFO Uploading status blob succeeded
2016/06/29 20:48:10.185708 INFO Uploading status blob succeeded
2016/06/29 20:48:35.336231 INFO Uploading status blob succeeded
2016/06/29 20:49:00.500373 INFO Uploading status blob succeeded
2016/06/29 20:49:26.733723 INFO Uploading status blob succeeded
2016/06/29 20:49:51.886801 INFO Uploading status blob succeeded
2016/06/29 20:50:17.044515 INFO Uploading status blob succeeded
2016/06/29 20:50:43.267796 INFO Uploading status blob succeeded
```

**Pull request merged**
