### PR TITLE
Add logging interval backoff for PA waiting for cloud-init provisioning

### PR DESCRIPTION
**Pull request by johnsonshi**
## Description

The WALinuxAgent PA excessively logs messages when it is waiting for cloud-init to finish provisioning. This PR decreases the log verbosity when the WALinuxAgent PA waits for cloud-init to copy the ovf-env.xml and to generate the ssh host keys.

---

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.

### Quality of Code and Contribution Guidelines
- [x] I have read the [contribution guidelines](https://github.com/Azure/WALinuxAgent/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by narrieta** [comment]
@anhvoms @trstringer could you take a look? thanks!

**Comment by trstringer** [comment]
Looks good to me!

**Review by pgombar — APPROVED** [review]

**Comment by pgombar** [comment]
Running end-to-end automation: https://tuxgold.corp.microsoft.com/job/AzLinux/job/DungeonCrawler/view/WALinuxAgent/job/DungeonCrawler.pagombar/1003

**Review by narrieta — APPROVED** [review]
LGTM

@pgombar will merge after running automation

**Comment by pgombar** [comment]
End-to-end automation ok, no new issues. There's a flaky test that failed on Travis, need to get permissions to restart the job.

**Pull request merged**
