### PR TITLE
Make IPoIB interface online

### PR DESCRIPTION
**Pull request by longlimsft**
Some Infiniband applications require IPoIB interface to be online for
address resolution to work. This patch makes the interface online during
provisioning. The return code is ignored as the link status doesn't need
to be checked and it doesn't affect its IP address.

## Description

Issue # 

---

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and Travis.CI is passing.

### Quality of Code and Contribution Guidelines
- [ ] I have read the [contribution guidelines](https://github.com/Azure/WALinuxAgent/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by narrieta** [comment]
> The return code is ignored as the link status doesn't need
> to be checked and it doesn't affect its IP address.

If the intention is to ignore the return code, then this call should be wrapped by try/except CommandError:

```
                        ip_command = ["ip", "link", "set", nic, "up"]
                        shellutil.run_command(ip_command)
```

**Comment by longlimsft** [comment]
> > The return code is ignored as the link status doesn't need
> > to be checked and it doesn't affect its IP address.
> 
> If the intention is to ignore the return code, then this call should be wrapped by try/except CommandError:
> 

This command always return 0 regardless of link status changes. The only time it will error out is when "nic" is an invalid name, in which case there is no need to execute the following command in the same try block.

Since it's in the same try block as the following command , there is no need to use another try block.

> ```
>                         ip_command = ["ip", "link", "set", nic, "up"]
>                         shellutil.run_command(ip_command)
> ```

**Comment by narrieta** [comment]
@longlimsft ok; will run automation

**Review by larohra — COMMENTED** [review]
Code looks good, running automation

**Review by larohra — APPROVED** [review]
Automation ok. LGTM

**Pull request merged**
