### PR TITLE
Fix clearlinux distro_name (#792)

### PR DESCRIPTION
**Pull request by chuyd**
Updating distro_name condition to match /usr/lib/os-release for current 
clearlinux releases.

Signed-off-by: Ornelas Aguayo, Jesus <jesus.ornelas.aguayo@intel.com>

### CODE REVIEW

**Comment by albertomurillo** [comment]
What about
```python
if distro.name == 'clearlinux'
    return ClearLinuxUtil()
```

And make distro.name return 'clearlinux' rather than the full name?

**Comment by brendandixon** [comment]
@chuyd We likely need to continue supporting older releases as well. What if you either checked a regex or a startswith for "clear linux "?

**Comment by rnesius** [comment]
I opened a new pull request with a fix that supports both old and new name.

**Comment by chuyd** [comment]
@brendandixon I updated the commit to support older releases

**Comment by chuyd** [comment]
@rnesius I updated the commit  to add support for previous and current Clear Linux OS for
Intel Architecure releases by searching the "Clear Linux" string
in osinfo[0] and returning clearlinux in distro_name, what do you think?

**Comment by brendandixon** [comment]
Addressed by #796

**Pull request closed without merging**
