### PR TITLE
Add Support for Huawei EulerOS

### PR DESCRIPTION
**Pull request by hufengwei**
waagent doesn't work fine for Huawei EulerOS because it doesn't handle EulerOS distribution.
With this fix, waagent is able to get_osutil  and get instance of eulerosDistro. Please help to review and merge the request, thanks!

### CODE REVIEW

**Comment by hglkrijger** [comment]
@hufengwei could you sign the CLA please?

**Comment by isula** [comment]
Great job!

**Comment by hufengwei** [comment]
@hglkrijger I have signed the CLA, would you please help merge the pull request? thanks!

**Comment by hglkrijger** [comment]
@hufengwei, thanks! We should be merging this in the next couple days.

**Pull request merged**
