### PR TITLE
Correct extension state and process management

### PR DESCRIPTION
**Pull request by brendandixon**
- Migrate extension state and status back to v2.0.x location
- Added restart telemetry
- Check if process is orphaned (cleanly exit if so)

Signed-off-by: Brendan Dixon <brendand@microsoft.com>

### CODE REVIEW

**Comment by hglkrijger** [comment]
lgtm

**Comment by brendandixon** [comment]
@hglkrijger I'm adding one more item before we merge this...

**Comment by brendandixon** [comment]
@hglkrijger Shall we now merge?

**Comment by hglkrijger** [comment]
yes, thanks

**Pull request merged**
