### PR TITLE
fix the regression for mounting resourcedisk on FreeBSD

### PR DESCRIPTION
**Pull request by ccic**

### CODE REVIEW

**Comment by ccic** [comment]
This issue takes impact on v2.2.2, and the result is FreeBSD with v2.2.2 has provisioning timeout issue.

**Comment by KylieLiang** [comment]
Hi team, could you please help review the fix? Can it be integrated to v2.2.2? Otherwise, it is difficult to manage the cases customers upgrade Agent by themselves. Thank you very much.

**Comment by mauriciodeliz** [comment]
Alguém tem problema com FreeBSD 10.3-release-p16 (PFSense 2.2.3)? A maquina inicia com "FALHA" na Azure.
loop

**Comment by ccic** [comment]
@mauriciodeliz Could you please list more details about how to install PFSense 2.3.3 on FreeBSD 10.3-release-p16? Can you start FreeBSD on Azure before you installed PFSense 2.3.3? It helps us to diagnose the issue if you can provide more details or background information.

**Comment by ccic** [comment]
@mauriciodeliz FreeBSD 10.3 published on Azure contains some fixes which have not been included in official FreeBSD 10.3-release-p16. See below. In addition, you also need to add "vfs.mountroot.timeout=300" in /boot/loader.conf to avoid potential issue.

43782d0-Hongjiang Zhang-Fri Dec 9 14:42:39 2016 +0800-hyperv/stor: Fix the failing of attach disk on LUN 8 on win2k12
7b0b73a-hongjiang zhang-Thu Oct 13 17:10:38 2016 +0800-hyperv/stor: Fix the regression of TRIM
57f33ae-Hongjiang Zhang-Mon Sep 19 16:29:07 2016 +0800-hyperv/storvsc: disable intr_shuffle_irqs on Hyper-V
3282f19-sephe-Mon Mar 21 07:16:30 2016 +0000-hyperv/vmbus: Implement bus_child_pnpinfo_str method
3d24e7d-sephe-Mon Mar 21 06:54:21 2016 +0000-hyperv: Factor out snprinf_hv_guid()
f8bc14b-hongjiang zhang-Thu Sep 8 14:02:20 2016 +0800-hyperv/storvsc: remove ATA driver with a decent way
febb2da-hongjiang zhang-Tue Aug 16 16:03:51 2016 +0800-hyperv/stor: Fix the issue of hot plugin more than 7 disks
b13bc8d-hongjiang zhang-Wed Aug 3 22:14:24 2016 +0800-hyperv/stor: Support UNMAP/TRIM for FreeBSD on Win2012R

**Comment by mauriciodeliz** [comment]
@ccic I just installed the PFsense ISO in the local environment "On premises" and did UPLOAD from VHD to Azure. I can access the machine and make customizations, but the machine presents "failure" in Portal Azure. It is slow to turn off and on.

**Comment by ccic** [comment]
@mauriciodeliz Did you install the required package? here is a doc for your reference: http://vaggeliskappas.com/2015/07/23/running-pfsense-as-an-azure-iaas-virtual-machine/

**Comment by mauriciodeliz** [comment]
I'm using this template.

I fixed the problem by removing the Azure machine and putting it back, after that it worked very well.

**Comment by aallee1** [comment]
How do we backup a VM running on Linux freeBSD? The azure backup fails with error message “unsupported OS”

**Pull request merged**
