### PR TITLE
wire.py#decode_config needs to handle empty strings (#486)

### PR DESCRIPTION
**Pull request by jinhyunr**
1. Add is_str_none_or_whitespace to textutil for string emptiness check
2. Update remove_bom to properly handle empty/none/whitespace string

### CODE REVIEW

**Comment by brendandixon** [comment]
@jinhyunr What if the string contains too few legitimate characters (e.g., "a")? Won't the code still fail?

**Comment by jinhyunr** [comment]
```python
def remove_bom(c):
    if not is_str_none_or_whitespace(c) and \
       str_to_ord(c[0]) > 128 and \
       str_to_ord(c[1]) > 128 and \
       str_to_ord(c[2]) > 128:
        c = c[3:]
    return c
```

in case of 'a', str_to_ord(c[0]) > 128 becomes False, so it will simply return 'a' as it is.

**Comment by brendandixon** [comment]
@jinhyunr I think you are missing my point: I can construct a string that is too short that will cause the method to throw an exception. My point is, that the fix evaluates for types of strings (e.g., all whitespace), where the exception occurs because the length is too short. The code must ensure sufficient characters exist.

**Comment by hglkrijger** [comment]
@jinhyunr - looks like a merge conflict with the hotfix, sorry. please take a look when you can.

**Pull request merged**
