### PR TITLE
drop cgroup support for rhel

### PR DESCRIPTION
**Pull request by nagworld9**
## Description

CX reported the waagent hang issue https://github.com/Azure/WALinuxAgent/issues/2674. RHEL team suspecting that Kernel bug in implementation of cgroups. Since the agent uses cgroups for resource governance, dropping the rhel support to be cautious and avoid potential widespread.
  
Issue # 

---

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made

### Quality of Code and Contribution Guidelines
- [ ] I have read the [contribution guidelines](https://github.com/Azure/WALinuxAgent/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by narrieta — APPROVED** [review]

**Comment by Klaas-** [comment]
Hi,
two things:
1) if rhel is affected so is centos
2) at least for me this only seems to happen on 7.9, not on 8.

**Comment by nagworld9** [comment]
@Klaas- It's not very clear what is the RCA and what distros really impacted.  At this point we only know rhel affected so we decide to drop the entire rhel versions to be on conservative side.

**Comment by Klaas-** [comment]
there should be zero functional difference between a centos 7 and a rhel 7 kernel. with centos stream it's a little different, but for 7 it's a clone. The literally just exchange some certs and strings https://git.centos.org/rpms/kernel/c/595b4ccbe0e0e84f193c39a24f4c78e3933ebee6?branch=c7 @nagworld9

**Comment by vittyvk** [comment]
I also don't quite understand why such a big hammer is being used here. RHEL kernels support cgroups and the problem (https://github.com/Azure/WALinuxAgent/issues/2674) is only observed on RHEL7. Why do we need to disable cgroup support for RHEL8 and RHEL9? I also agree that Centos and RHEL should have the same behavior.

**Comment by nagworld9** [comment]
@vittyvk Today our agent only uses cgroup v1 and not supporting the RHEL9 as this by default, mounts and utilizes cgroups-v2. 
We are in the process of releasing new version of agent and we don't want to block this deployment until we know the RCA. So, with this uncertainty we felt it's safe to drop support for all rhel and centos and retake our deployment to avoid potential widespread as we are setting the cpu quota to 50% in the new version.

**Comment by Klaas-** [comment]
@vittyvk they also dropped it for centos after my push via https://github.com/Azure/WALinuxAgent/pull/2689

**Comment by nagworld9** [comment]
@Klaas- @vittyvk If it was miscommunicated earlier, I just want to make it clear that the changes here do not drop support for RHEL, they simply stop setting up a CPU quota on the agent.

**Comment by Klaas-** [comment]
I think we understood that :)

**Comment by narrieta** [comment]
Fixes #2674

**Pull request merged**
