### PR TITLE
Set the umask prior to file creation

### PR DESCRIPTION
**Pull request by edneville**

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
cc: @szarkos to take a look.
If this gets merged, we need to backport to 2.1/`develop` branch.

**Comment by szarkos** [comment]
Looks OK, I have no concerns.

**Comment by hglkrijger** [comment]
@edneville, if we update the 2.0 version, the 2.1 version should be updated as well. This is in [resourcedisk/default.py](https://github.com/Azure/WALinuxAgent/blob/develop/azurelinuxagent/daemon/resourcedisk/default.py#L209). While you make that change, could you rebase and submit against the develop branch?

**Comment by ahmetalpbalkan** [comment]
Closing in favor of #316.

**Pull request closed without merging**
