### PR TITLE
Fix issue Azure/WALinuxAgent#388

### PR DESCRIPTION
**Pull request by krkhan**

### CODE REVIEW

**Comment by hglkrijger** [comment]
lgtm

**Comment by brendandixon** [comment]
@hglkrijger Tests would be good. I did verify the code against the Windows Guest Agent. This is the correct format.

**Comment by hglkrijger** [comment]
@brendandixon, we can also take this now if we need to and add tests later.

**Comment by brendandixon** [comment]
@hglkrijger @krkhan I'm fine with that. It's a small change. It matches the Windows code. Oddly, I do not see corresponding code in the waagent2.0 file. Perhaps there was a format change and the v2.1.x branch missed full implementation?

**Comment by brendandixon** [comment]
@hglkrijger Will our pipeline catch errors here? That is, if an extension writes status, will the pipeline detect that the agent correctly forwards it?

**Comment by hglkrijger** [comment]
@brendandixon - not sufficiently. Our automation today checks the local settings file for the expected status, but does not check that it is forwarded out. We can certainly add more rigorous checks in the upcoming replacement pipeline.

**Pull request merged**
