### PR TITLE
added cloudlinux support

### PR DESCRIPTION
**Pull request by JohnKepplers**
## Description
https://www.cloudlinux.com/
CloudLinux OS is a Linux distribution marketed to shared hosting providers.

Issue # 

---

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] If applicable, the PR references the bug/issue that it fixes in the description.
- [x] New Unit tests were added for the changes made

### Quality of Code and Contribution Guidelines
- [x] I have read the [contribution guidelines](https://github.com/Azure/WALinuxAgent/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by JohnKepplers** [comment]
@larohra 
Please review! This PR is similar to https://github.com/Azure/WALinuxAgent/pull/2219

**Comment by JohnKepplers** [comment]
@ZhidongPeng @dhivyaganesan @narrieta @kevinclark19a @nagworld9
Could you please check my PR? It's similar to https://github.com/Azure/WALinuxAgent/pull/2219.

**Review by larohra — APPROVED** [review]
LGTM. Running automation to confirm no regressions, will post update here once I get a green run

**Review by kevinclark19a — APPROVED** [review]

**Comment by larohra** [comment]
Automation ok

**Pull request merged**
